CMakeLists.txt, CompileHowto.txt, HyperionConfig.h.in, include/grabber/FramebufferWrapper.h, include/utils/Image.h, libsrc/grabber/CMakeLists.txt, libsrc/grabber/framebuffer/CMakeLists.txt, libsrc/grabber/framebuffer/FramebufferFrameGrabber.cpp, libsrc/grabber/framebuffer/FramebufferFrameGrabber.h, libsrc/grabber/framebuffer/FramebufferWrapper.cpp, src/hyperiond/CMakeLists.txt, src/hyperiond/hyperiond.cpp
Added the framebuffer grabber as alternative for non-rpi devices. Tested on cubox-i with xbian v1.0RC3 and openelec 5.0
=> Frambuffer grabber support

libsrc/leddevice/LedDeviceFactory.cpp, libsrc/leddevice/LedDevicePhilipsHue.cpp, libsrc/leddevice/LedDevicePhilipsHue.h
Added configuration options for the username and the transition time of the lights.
=> Support for philips hue

libsrc/leddevice/CMakeLists.txt, libsrc/leddevice/LedDeviceAtmo.cpp, libsrc/leddevice/LedDeviceAtmo.h, libsrc/leddevice/LedDeviceFactory.cpp
http://ca.rstenpresser.de/index.php/atmo-main.html
=> Carsten Atmolight support

include/hyperion/Hyperion.h, include/hyperion/LedString.h, libsrc/hyperion/Hyperion.cpp, libsrc/hyperion/hyperion.schema.json
=> Added rgbOrder config for each led

libsrc/leddevice/LedDeviceAPA102.cpp
End frame fixed using info from https://cpldcpu.wordpress.com/2014/11/30/understanding-the-apa102-superled/
=>  End Frame fixed (Issue #361)

libsrc/leddevice/CMakeLists.txt, libsrc/leddevice/LedDeviceAdalight.h, libsrc/leddevice/LedDeviceAdalightApa102.cpp, libsrc/leddevice/LedDeviceAdalightApa102.h, libsrc/leddevice/LedDeviceFactory.cpp
I have added suprt for APA102 to be used with Adalight (no changes needed to Adalight) I have tested on 86 leds. Works exactly the same as ws2801. 
I hope this will be useful for others as well :)
Regards
Jacek
=> APA102 implementation for Adalight

libsrc/leddevice/LedDeviceAPA102.cpp, libsrc/leddevice/LedDeviceAdalightApa102.cpp
Problem with end frame was not only endFrameSize, but led index. Also, reduced a bit the size of endFrame.
=> APA102 end frame fixed (this time for real)

libsrc/leddevice/LedDevicePhilipsHue.cpp
Added the new Lightstrip plus, hue go and Aura. The first two come with
a new Gamut profile and the Aura is from Living Colors.
=> Added some more hue devices and Gamut-Profile

libsrc/boblightserver/BoblightClientConnection.cpp
I have written a few clients for boblightd in the past and tried to connect them to hyperion.
There occured two issues that are solved with these changes:
- I got "unknown boblight message" for all messages I sent, solved by trimming received messages
- it was not possible to change the color because of a wrong decimal separator, solved by replacing comma with point
=> make hyperion more robust

libsrc/leddevice/LedDevicePhilipsHue.cpp
=> minor qt5 fix

doc/datasheets/fadecandy_opc_protocol.md, libsrc/leddevice/LedDeviceFactory.cpp, libsrc/leddevice/LedDeviceFadeCandy.cpp, libsrc/leddevice/LedDeviceFadeCandy.h
increase fadecandy maximum amount of leds
remove debug code
=> fadecandy fix

libsrc/leddevice/LedDeviceAPA102.cpp
Reverts tvdzwan/hyperion#484
was working before so this merge was not needed
sorry for the inconvenience
=> Revert "Update LedDeviceAPA102.cpp by pcaffardi"

bin/create_release.sh, bin/install_hyperion.sh
this issue caused a lot of confusion to many users downloading an outdated binary with bugs that where corrected since ages
**@tvdzwan PLEASE notice the changed create script for the next binary release**
=> corrected install script rpi binary filename

include/blackborder/BlackBorderDetector.h, libsrc/blackborder/BlackBorderProcessor.cpp
added bottom right to osd mode
i think this is the final commit if no more ideas or requests
=> Blackborder Improved +

libsrc/leddevice/LedDevicePhilipsHue.cpp
With newer bridges, the light ids are not automatically ordered anymore. Thus, the code queries the bridge for available light ids.
=> Reads hue light ids in case the user did not supply any.

src/hyperiond/hyperiond.cpp
This patch fixes 2 things:
- static boot color is shown before boot effect
- internal grabber overrules boot effect when starting
If boot duration is set to infinity (0) the boot priority value is used and normal effects can overrule the boot effect.
If duration is not infinity, prio is set to 0 to avoid internal grabbers overrule the boot effect.
This PR is realted to ideas/discussions in #535 #475 #437
**example usages:**
boot efx: "mood bloobs"
duration: 0
prio: 990
usage of standalone grabber like hyperion-dispmanx / hyperion-v4l2 / ...
On boot the effect is shown for ever. Then the ambilight/grabber is activated and ambi lights shown.
When standalone grabber is killed the boot effect ("mood bloobs") shown.
boot efx: "rainbow"
duration: 3000
prio: 990
on startup the rainbow is shown …
=> fix bootsequence

libsrc/leddevice/LedDevicePhilipsHue.cpp, libsrc/leddevice/LedDevicePhilipsHue.h
The loop goes one index too far. Not a problem later but not necessary either.
=> Improved validity checks and memory footprint for Philips Hue

include/effectengine/ActiveEffectDefinition.h, include/effectengine/EffectEngine.h, include/hyperion/Hyperion.h, libsrc/effectengine/Effect.h, libsrc/effectengine/EffectEngine.cpp, libsrc/hyperion/Hyperion.cpp, libsrc/jsonserver/JsonClientConnection.cpp
**1.Tell us something about your changes.**
With this code we are able to get the current active and running effects over the json interface.
Send the JSON Object : {"command": "serverinfo"} or use "hyperion-remote -l"
**2. If this changes affect the .conf file. Please provide the changed section.**
no.
**3. Reference a issue**
#548
=> get current state (active Effects) over JSON Interface

libsrc/jsonserver/JsonClientConnection.cpp
**1.**
Sorry my English is not so good. 
Send the JSON Object : {"command": "serverinfo"} or use "hyperion-remote -l"
best regards
Paulchen Panther
**2.**
No
**3.**
#398
=> Feature Request - Get current LED color (JSON API)

effects/mood-blobs-full.json, effects/mood-blobs.py
Small change to allow a random start hue for mood blobs - adds a bit of
spice instead of starting at the same color every time.
=> Allow random mood blobs color, set mood-blobs-full to random

doc/UDP_led_driver.txt, libsrc/leddevice/LedDeviceUdp.cpp
I've add some very simple support for TPM2.net protocol to the UDP output.
Minimal documentation can be found in doc/UDP_led_driver.txt
=> added simple TPM2.net support to UDP output

libsrc/hyperion/MultiColorAdjustment.cpp
Only apply color channel if color is dominant. Grey color independent from color channels. Linear increase of color channel from grey to maximum.
[see forum thread](https://hyperion-project.org/threads/better-color-adjustment.104/)
=> Better color adjustment

libsrc/hyperion/Hyperion.cpp
Change order from "Adjustment -> Transform" to "Transform -> Adjustment"
[see forum thread](https://hyperion-project.org/threads/better-color-adjustment.104/)
=> Reorder Transform and Adjustment

src/hyperiond/CMakeLists.txt, src/hyperiond/hyperiond.cpp
spawn multiple hyperiond when multiple configs given on command line
example
```
./hyperiond hyperion.hue.config.json hyperion.forwarder.config.json
```
if a given config is not found, it is ignored. If none of given configs exists, hyperion start is aborted with message.
if used for forwarder things, it is the best if config of forwarder is last in the list.
hyperiond instances started with 5 seconds delay to avoid race conditions.
Be aware that output of command line is a mess with more then one deamon. 
no
=> start multiple hyperions

include/hyperion/Hyperion.h, libsrc/hyperion/Hyperion.cpp, libsrc/jsonserver/JsonClientConnection.cpp
Improved JSON Serverinfo. Active LED Color in RGB, HSL & HEX
Send the JSON Object : {"command": "serverinfo"} or use "hyperion-remote -l"
no
=> Update Json Interface (Active LED Color)

include/grabber/X11Grabber.h, include/protoserver/ProtoConnection.h, include/protoserver/ProtoConnectionWrapper.h, include/protoserver/ProtoServer.h, libsrc/grabber/x11/X11Grabber.cpp, libsrc/protoserver/ProtoClientConnection.cpp, libsrc/protoserver/ProtoClientConnection.h, libsrc/protoserver/ProtoConnection.cpp, libsrc/protoserver/ProtoConnectionWrapper.cpp, libsrc/protoserver/ProtoServer.cpp, libsrc/protoserver/message.proto, src/hyperion-x11/X11Wrapper.cpp, src/hyperion-x11/X11Wrapper.h, src/hyperion-x11/hyperion-x11.cpp, src/hyperiond/hyperiond.cpp
**Only in German Language:**
Die XBMC Video Checker Benachrichtigung wird nun auch über das proto Interface gesendet.
Dadurch startet und stoppt der X11 Grabber  nun auch korrekt.
Nein
[REQUEST Add KodiCheck to hyperion-x11](https://hyperion-project.org/threads/add-kodicheck-to-hyperion-x11.138/)
=> Hyperion X11 KodiCheck

src/hyperiond/hyperiond.cpp
proto and json server is always on. If not configured in config, server started with default settings.
no
=> make proto and json server permanent.

src/hyperiond/hyperiond.cpp
fix typo and now beta should compile
=> Refactoring - typo fix

libsrc/utils/Logger.cpp
=> fix build on osx

libsrc/jsonserver/JsonClientConnection.cpp
IMPORTANT: Please don´t commit to master, we will test your changes first at the beta branch!
Fixing the detection of the color Black
no
#701 
Note: For further discussions use our forum: forum.hyperion-project.org
=> Fixing Check if LED Color not Black

config/hyperion.config.json.example, libsrc/hyperion/Hyperion.cpp, libsrc/hyperion/LinearColorSmoothing.cpp, libsrc/hyperion/LinearColorSmoothing.h, libsrc/utils/Logger.cpp
smoothing: integrate option for continuousOutput + updateDelay fix from hyperion.ng
logger: fix possible buffer overflow
=> smoothing fix

bin/install_hyperion.sh
=> Add PlexMediaPlayer

CompileHowto.txt
=> Fix typos in CompileHowto.txt

libsrc/hyperion/LinearColorSmoothing.cpp
Fixed LinearColorSmoothing in continuousOutput=false mode to not consume CPU for no reason after the output has settled.
=> Fix LinearColorSmoothing CPU usage

CompileHowto.txt
`brew install qt4`  doesn't work, I have tested the proposed changes.
=> Update mac qt4 installation

CompileHowto.txt
=> update CompileHowto for OSMC

CompileOnOrangepi.md
1. Tell us something about your changes.
How to compile on Orange pi md is added.
2. If this changes affect the .conf file. Please provide the changed section
This Does not effect conf file 
3. Reference a issue (optional)
No issue reference
=> CompileOnOrangepi Document added
