hyperion-project/hyperion

- libsrc/leddevice/LedRs232Device.cpp
Fixes 3rd comment of https://github.com/tvdzwan/hyperion/issues/351
This is not a fix for the whole issue, just partly.
If you unplug the device it will attempt to reconnect to it in 3 seconds. Then you can run hyperion always at startup without having the Arduino/Serial device connected, but it will find it when you plug it in.
> Fix RS232 reconnect bug

- libsrc/leddevice/LedDevicePhilipsHue.h
This fixes a compatibility issue when compiling with gcc 4.6 (which is
the version distributed with raspbian by default)
See #368
> Maintain compatibility with gcc 4.6

- libsrc/leddevice/CMakeLists.txt
- libsrc/leddevice/LedDeviceAdalight.h
- libsrc/leddevice/LedDeviceFactory.cpp
- libsrc/leddevice/LedDevicePaintpack.cpp
- libsrc/leddevice/LedDevicePaintpack.h
- libsrc/leddevice/LedDeviceRawHID.cpp
- libsrc/leddevice/LedDeviceRawHID.h
- libsrc/leddevice/LedHIDDevice.cpp
- libsrc/leddevice/LedHIDDevice.h
This PR adds a new generic HID device which relies on the already used HIDAPI. This way we do not need to duplicate the code for the HID API handling. It also fixes reconnection issues. The new HID Device will reconnect after 3 seconds if connection was lost. On top of that you can now (optionally) change the USB PID and VID via the json config file.
On top of that a new RawHID device was added which works with the current dev version of the HID Project. This way you can simply use an Arduino (as keyboard!) to receive data, not even a real RawHID device is required (but would also work). Both feature and report out is supported.
More information about this can be found here:
https://github.com/arduino/Arduino/pull/4105
If you like to, you can adapt this api to other led devices. I did …
> Add RawHID Device + HID API Device

- CompileHowto.txt
Downloading the raspi firmware took me forever. Since its only copied once and not really important to have the whole history, I added `--depth 1` to it. Otherwise it trashes the SD card.
Also I added a note for the normal hyperion git, since hyperion also has all binaries in the history which is pretty time and space consuming. I didnt add it by default, since if people want to push commits I think this would not work properly. See this: https://github.com/tvdzwan/hyperion/issues/392
> Typos in Compile Instructions + clone only latest git

- libsrc/leddevice/CMakeLists.txt
- libsrc/leddevice/LedDeviceFactory.cpp
- libsrc/leddevice/LedDeviceFadeCandy.cpp
- libsrc/leddevice/LedDeviceFadeCandy.h
I've got the Adafruit FadeCandy Controller (https://www.adafruit.com/products/1689) working. This device uses the OPC Standard (http://openpixelcontrol.org/). You can use the driver also for other OPC devices.
This implemention uses the "fcserver" via network. Set your "output" in hyperion.config.json to the fcserver address (e.g. 127.0.0.1 ). If you want to set an individual port, set "port" variable in config too.
(tested on rpi 1 and linux)
> add FadeCandy/OPC device support

- include/blackborder/BlackBorderDetector.h
- include/blackborder/BlackBorderProcessor.h
- libsrc/blackborder/BlackBorderProcessor.cpp
blackborderprocessor:
added a tolerance for switching to smaller border. will prevent a lot of false positives resulting from size decimation/bad signal/flickering.
blackborderdetector:
changed the way the border is detected - the function will try check vertical and horizonal separate and check at 1/3 1/2 and 2/3 of the width/height (3 pixel check) till it finds a non black pixel
which will also decrease the number of false positives.
will use a little bit more resources but seems more stable in the end
> Blackborder Improved

- include/blackborder/BlackBorderDetector.h
- libsrc/blackborder/BlackBorderProcessor.cpp
- test/TestBlackBorderProcessor.cpp
BlackBorderProcessor.cpp:
The new changes ignore false small borders (no reset of consistance)
as long as the previous stable state returns within 10 frames
and will only switch to a new border if it is realy detected stable >50 frames.
More information in sourcecode
BlackBorderDetector.h:
Still checking 3 lines horizontal and vertical.
But instead of checking only left and top the center "scanlines" will check bottom and right side of the image to avoid detecting small border when there is only a dark area on the left side or the top area of the image.
> Blackborder Improved +

- config/hyperion.config.json
- config/hyperion_x86.config.json
- src/hyperiond/hyperiond.cpp
When boot effect is set to "stay forever" (duration 0), no effect can't be set afterwards.
Now it is settable in config and everybody can set the value to something that fits the needs.
this PR should fullfill @solidewebservices issue in issue #437 and is usefull for issue #77 too
> make priority of boot effect adjustable.

- config/hyperion.config.json
- include/blackborder/BlackBorderDetector.h
- include/blackborder/BlackBorderProcessor.h
- include/hyperion/ImageProcessor.h
- include/hyperion/ImageProcessorFactory.h
- libsrc/blackborder/BlackBorderDetector.cpp
- libsrc/blackborder/BlackBorderProcessor.cpp
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/ImageProcessor.cpp
- libsrc/hyperion/ImageProcessorFactory.cpp
- test/TestBlackBorderProcessor.cpp
fixed a bug that caused undefined behaviour in detection,
causing it to get stuck at 0,0 border detection.
Also made json config accessable in blackborder classes for easy adjusting values that are static in current build.
Added different detection modes.
see config/hyperion.config.json
```
"blackborderdetector" :
{
"enable" : true,
"threshold" : 0.01,
+		"unknownFrameCnt": 600,         <- optional
+		"borderFrameCnt" : 50,          <- optional
+		"maxInconsistentCnt" : 10,      <- optional
+		"blurRemoveCnt": 1,             <- optional
+		"mode" : "default"              <- optional
}
```
Modes:
**default**: 3 scanlines per direction - fastest detection so far (because of the nature of movies to have none black content in the center area;)
**classic**: the original implementation - needs …
> Blackborder Improved + (bugfix and enhancement)

- libsrc/leddevice/LedDeviceAPA102.cpp
original commit message by pcaffardi (https://github.com/pcaffardi/hyperion/commit/2d714e6eb075ec57e0973839fe96d2d7a051c57f):
> This fix the previous limit of 64 APA102 leds, because of too short end frame. Now the end frame is computed accordling to this documentation: https://cpldcpu.wordpress.com/2014/11/30/understanding-the-apa102-superled/. Tested on my 98 leds, it works fine.
> 
> I suggest to modify hyperion to allow LED drivers to apply the brightness parameter because APA102 has a parameter for that, without the need to elaborate RGB color to simulate it (result is wrong colors!). Is it possible to introduce such parameter in LED drivers and let the driver apply that?
this fix is mentioned in #480 #364 and #206 
original authors seems inactive and this patch is out there since a …
> Update LedDeviceAPA102.cpp by pcaffardi

- libsrc/blackborder/BlackBorderDetector.cpp
- libsrc/hyperion/ImageProcessorFactory.cpp
Missing 'ceil' function on OSX
> Fix compile issue for missing ceil function

- CMakeLists.txt
- libsrc/effectengine/CMakeLists.txt
If you want to compile for OpenElec on Raspberry Pi, you must use Python 2.7
> Update CMakeLists.txt for OpenElec -> Python 2.7

- .gitmodules
- CMakeLists.txt
- HyperionConfig.h.in
- dependencies/CMakeLists.txt
- libsrc/leddevice/CMakeLists.txt
- libsrc/leddevice/LedDeviceFactory.cpp
- libsrc/leddevice/LedDeviceWS281x.cpp
- libsrc/leddevice/LedDeviceWS281x.h
I've noticed that @jgarff has been updating his PWM using DMA ws281x library to keep pace with differences between pi versions.  He's also parameterized the library nicely so it'll be easy to accomodate many different models with different DMA configurations. It also has the added bonus of working on my hardware. @Zappatron's fork works for me as well, but has the unfortunate effect of replacing RPi 1 support.
I've added a new LED driver that is a wrapper around jgarff's library so that hyperion gets the benefits of his recent improvements as well as hopefully future ones too.  At the moment this adds support for Pi 2 and Pi Zero over what is already in hyperion.  It will probably also give Pi 3 support, but I won't be able to test until mine arrives.
I added this as an additional driver …
> Add new WS281x driver

- libsrc/leddevice/LedDeviceFactory.cpp
- libsrc/leddevice/LedDeviceWS281x.cpp
- libsrc/leddevice/LedDeviceWS281x.h
The RPi 2 and 3 have two PWM channels and 3 PWM pins available to the
gpio header.  BCM18 and BCM12 run on PWM channel 0.  BCM13 runs on PWM
channel 1.  This change allows BCM13 to be used by allowing the PWM
channel to be specified.
Adds optional "pwmchannel" parameter to the "device" section.  If unspecified, has the default of 0 which was used before this change.  So, all old .conf files should work the same as they did before.
> Add ws281x driver parameter for PWM channel

- libsrc/leddevice/LedDeviceAtmoOrb.cpp
- libsrc/leddevice/LedDeviceAtmoOrb.h
- libsrc/leddevice/LedDeviceFactory.cpp
Added new AtmoOrb options:
- Choose between Orbs internal smoothing or that of Hyperion  and defined by **useOrbSmoothing** bool setting (true = external Orb smoothing)
- minimal color (0-255) difference to override smoothing so that if current and previously received colors are higher than diff we override Orbs external smoothing and is defined by **skipSmoothingDiff** integer setting
skipSmoothingDiff setting allows for faster transitions when the minimal color difference is defined (0-255), for instance if you go from full white to black it can clear smoothing right away for instant color change, this is only used when Orbs smoothing is enabled (useOrbSmoothing = true);
**2.** If this changes affect the .conf file. Please provide the changed …
> AtmoOrb smoothing additions

- libsrc/leddevice/LedDeviceAtmoOrb.cpp
- libsrc/leddevice/LedDeviceAtmoOrb.h
Compares last color send to new one and if identical skips command for the AtmoOrb device, this reduces the network load and makes sure we don't keep sending duplicate ones.
> AtmoOrb LedDevice - only process new commands and skip identical

- libsrc/leddevice/LedDeviceAtmoOrb.cpp
This reverts the recent change for the AtmoOrb device to skip colors if identical to last send, reason is that in some cases UDP packets might get lost over WiFi which will result in smoothing being off.
This is most noticeably on turn off / clear LED events where it might miss it and leave the Orbs on with the last colors.
> AtmoOrb device - removed skip same color change

- libsrc/xbmcvideochecker/XBMCVideoChecker.cpp
Kodi video checker patch to make it compliant with their recent JSON RPC API specs:
http://kodi.wiki/view/JSON-RPC_API/v6
ID should be listed last as otherwise this error will occur:
`Kodi Message: {"error":{"code":-32601,"message":"Method not found."},"id":666,"jsonrpc":"2.0"}`
For reference:
https://hyperion-project.org/threads/kodicheck-picture-modus-bad-detection-rate.90
> Kodi video checker bugifx

- include/grabber/DispmanxFrameGrabber.h
- include/grabber/DispmanxWrapper.h
- libsrc/grabber/dispmanx/DispmanxFrameGrabber.cpp
- libsrc/grabber/dispmanx/DispmanxWrapper.cpp
- src/hyperion-dispmanx/DispmanxWrapper.cpp
- src/hyperion-dispmanx/DispmanxWrapper.h
- src/hyperion-dispmanx/hyperion-dispmanx.cpp
- src/hyperiond/hyperiond.cpp
I had a closer look at issue #367 and seem to have found out why it fails and how to fix it:
Reading data from dispmanx only works correctly if the pitch is a multiple of 64 (i.e. the image/grabber width is a multiple of 16). Also reading only a part of the image (eg in 3DSBS mode) doesn't work as expected and produces garbage.
I fixed these issues by capturing to a separate buffer and then manually copying the capture data to the image if required.
In 2D mode or if the image is sized appropriately (eg width=128) we capture directly into the image buffer as before, so there'll be no performance impact in these situations.
Since we need to copy parts of the image in some occasions I went ahead and added support for image cropping (similar to the V4L2 grabber).
This helps people with old …
> dispmanx: fix grabber issues with certain widths and support cropping

- CMakeLists.txt
- bin/create_all_releases.sh
- bin/create_release.sh
- cmake/cmake_uninstall.cmake.in
- src/hyperion-aml/CMakeLists.txt
- src/hyperion-dispmanx/CMakeLists.txt
- src/hyperion-framebuffer/CMakeLists.txt
- src/hyperion-osx/CMakeLists.txt
- src/hyperion-remote/CMakeLists.txt
- src/hyperion-v4l2/CMakeLists.txt
- src/hyperion-x11/CMakeLists.txt
- src/hyperiond/CMakeLists.txt
general:
1. make life for people who compile hyperion a bit easier by providing "make install" "make uninstall" and a cmake PLATFORM option to reduce chance of messing up cmake options
2. code cleanup for cmakelists and bin/create_all_releases.sh
details:
1. now you can use make install and make uninstall. To get this working you have to provide an install prefix
`cmake -DINSTALL_PREFIX=/usr/local ..`
to install to /usr/local
or
`cmake -DINSTALL_PREFIX=/opt/hyperion ..`
to install to /opt/hyperion.
Currently this will install all binaries, effects and the service files. The service files aren't activated, you have to copy/link them manually if you wish. 
This part can be better - consider this as a start.
Normally you have to provide a list with cmake flags. 
e.g.:
`cmake …
> build script optimization

- include/utils/HslTransform.h
- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/hyperion.schema.json
- libsrc/jsonserver/JsonClientConnection.cpp
- libsrc/jsonserver/schema/schema-transform.json
- libsrc/utils/HslTransform.cpp
- src/hyperion-remote/JsonConnection.cpp
- src/hyperion-remote/JsonConnection.h
- src/hyperion-remote/hyperion-remote.cpp
As suggested in the [forum](https://hyperion-project.org/threads/better-color-adjustment.104/#post-641) I added a minimum luminance variable to the HSL transform. This variable can be used to brighten all dark colors including black to provide a led "backlight" in dark scenes. I hope I found all necessary places in the hyperion code and json schemas. I also added the variable to the hyperion-remote as 'n' parameter.
> Minimum luminance for backlight in dark scenes

- include/grabber/X11Grabber.h
- libsrc/grabber/x11/X11Grabber.cpp
- src/hyperion-x11/CMakeLists.txt
- src/hyperion-x11/X11Wrapper.cpp
- src/hyperion-x11/X11Wrapper.h
- src/hyperion-x11/hyperion-x11.cpp
**Sorry but only in German Language.**
1. Der X11 Grabber unterstützt nun auch die [XRender Erweiterung](https://en.wikipedia.org/wiki/X_Rendering_Extension) soweit diese vorhanden ist. Sollte diese nicht vorhanden sein, siehe Punkt 3.
2. Die Unterstützung der [MIT-SHM Erweiterung](https://en.wikipedia.org/wiki/MIT-SHM) ist weiterhin vorhanden. Sollte diese nicht vorhanden sein, siehe Punkt 3.
3. Die Ausweichmöglichkeit (XGetImage) für ältere Systeme wurde wieder hinzugefügt.
Diese lässt sich auch explizit mit den Parameter "-x" oder "--xgetimage" erzwingen.
Nein
1. #282 
2. …
> XRender support for X11 Grabber

- libsrc/effectengine/EffectEngine.cpp
tune output for effect folder loading. Prints successfully loaded folders.
When no effect found an error is printed
example output
`EFFECTENGINE INFO: 26 effects loaded from directory /opt/hyperion/effects`
or the error case (2 dirs in config, both exists, but contain no effect)
```
EFFECTENGINE INFO: 0 effects loaded from directory e1
EFFECTENGINE INFO: 0 effects loaded from directory e2
EFFECTENGINE ERROR: no effects found, check if your effect directories are valid and contain effects
```
no
https://hyperion-project.org/threads/effectengine-add-all-paths-to-json.101/
> better output for effect path loading

- libsrc/hyperion/Hyperion.cpp
- libsrc/hyperion/LinearColorSmoothing.cpp
- libsrc/hyperion/LinearColorSmoothing.h
- libsrc/utils/RgbChannelCorrection.cpp
in current implementation activated color smoothing sends periodically to led device. It also sends data when no new data is available and smoothing buffer is empty. 
This is wasted cpu power and can lead to unwanted effects. see issue #318 
This PR changes this behaviour. The smoothing sends only when data available, as it does when smoothing is switched off.
additional: I remove some compiler warnings from color correction code
no
#318
> prevent colorsmoothing from flooding led device

- src/hyperion-aml/CMakeLists.txt
IMPORTANT: Please don´t commit to master, we will test your changes first at the beta branch!
when building with -DENABLE_QT5=ON and no qt4 is installed, build will fail. qt4 modules are conditionaly used few lines below so this is just clean up.
Note: For further discussions use our forum: forum.hyperion-project.org
> [aml] do not unconditionaly use qt4 modules

- libsrc/utils/HslTransform.cpp
Set the saturation to 0 when apllying backlight. [See forum](https://hyperion-project.org/threads/better-color-adjustment.104/page-2#post-1668).
> Colorless Backlight

- libsrc/leddevice/LedDeviceFactory.cpp
**1.** 	Set default output device for WS2812SPI. With this change the WS2812SPI device works with Hypercon out of the box.
With this change the WS2812SPI device works with Hypercon out of the box. Otherwise a manual json edit is required to get the device working.
> Set default output device for WS2812SPI

- CompileHowto.txt
the name of the package is libqt4-dev not libQt4-dev
IMPORTANT: This repository no longer accepts new features or additions. Just bugfixes! Please commit to the repository "hyperion.ng" for new features.
> fixed name of libqt4 for ubuntu repositories

- .gitmodules
- dependencies/CMakeLists.txt
This includes support for newer RPI hardware versions.
It's been a while since i've had the pleasure of doing pull requests with updated submodules.
Can someone please check that this works for them too?
IMPORTANT: This repository no longer accepts new features or additions. Just bugfixes! Please commit to the repository "hyperion.ng" for new features.
Updated hyperion-project master branch to latest version
small modifications to CMake file to support the new version
nope
All those people who needed to hack the rpihw.c file and build from source so this would work with newer RPI hardware versions (like CM, ZeroW...)
> Updated rpi_ws281x submodule to latest commits

- include/utils/Image.h
Add a missing include for cassert to fix the -fpermissive compiler
error.
This fixes building hyperion on Arch Linux or any other distro with GCC 7.2
Fixes issue #766
> Fix no decleration of `assert` with GCC 7.2

- libsrc/leddevice/LedDeviceWS281x.cpp
I got segfaults when using an SK6812 stripe with hyperiond on a raspberry 2B V1.1. The strandtest.py from the ws281x submodule worked flawlessly.  I've added a init for the led_string which fixes the issue for me. 
I think this applies to #793
Thanks for your work. Hyperion is awesome.
> initialized led_string to prevent segfaults

- libsrc/leddevice/LedDevicePhilipsHue.cpp
Philips Hue ColorGamut A/B/C Values correction + New Models:
LCT015, LCT016, LCT024
> Philips Hue fix - correct API ColorGamut A/B/C Values + New Models

- bin/install_hyperion.sh
On my old Raspberry Pi1 B, cat /proc/cpuinfo gives :
> processor       : 0
> model name      : ARMv6-compatible processor rev 7 (v6l)
> BogoMIPS        : 697.95
> 
> Features        : half thumb fastmult vfp edsp java tls
> CPU implementer : 0x41
> CPU architecture: 7
> CPU variant     : 0x0
> CPU part        : 0xb76
> CPU revision    : 7
> 
> Hardware        : BCM2835
> Revision        : 000d
> Serial          : 0000000053cd43f1
> Fix RPI1 detection in installation script

- include/effectengine/ActiveEffectDefinition.h
- include/effectengine/EffectEngine.h
- libsrc/effectengine/Effect.cpp
- libsrc/effectengine/Effect.h
- libsrc/effectengine/EffectEngine.cpp
- libsrc/jsonserver/JsonClientConnection.cpp
Please be lenient with me, because this is the first pull request i had ever made.
I have added a name property in the Effect class to make it possible to get the name of the active effect in the 'serverinfo' JSON command results. I wouldn't name it a feature, it's more a bugfix, because without these changes, it isn't easily possible to get the current effect and compare it with a list of available effects.
Output before changes:
```
{   'info': {   'activeEffects': [   {   'args': {   'blobs': 5,
'color': [0, 255, 0],
'hueChange': 60.0,
'reverse': False,
'rotationTime': 60.0},
'priority': 100,
'script': '/root/hyperion/effects//mood-blobs.py',
'timeout': 0}],
'activeLedColor': [],
'adjustment': [   {   'blueAdjust': [0, 0, 255],
'greenAdjust': [0, 255, 0],
'id': 'default',
...
``` …
> Added effect name to JSON 'serverinfo' output in activeEffects

- libsrc/xbmcvideochecker/XBMCVideoChecker.cpp
kodi 18 had a breaking change to the resume after pause.
see https://github.com/hyperion-project/hyperion/issues/816
> fix resuming from paused in kodi 18

- CMakeLists.txt
- CompileHowto.txt
- HyperionConfig.h.in
- config/hyperion.config.json.example
- include/grabber/OpenCVGrabber.h
- include/grabber/OpenCVWrapper.h
- libsrc/grabber/CMakeLists.txt
- libsrc/grabber/opencv/CMakeLists.txt
- libsrc/grabber/opencv/OpenCVGrabber.cpp
- libsrc/grabber/opencv/OpenCVWrapper.cpp
- src/hyperiond/CMakeLists.txt
- src/hyperiond/hyperiond.cpp
I have a USB HDMI capture device which I wanted to use for my Ambient Light project. Unfortunately, it only supports MJPEG pixel format and looks like existing V4L2 grabber does not support that pixel format. Device worked well with my custom Python + OpenCV script and I hacked Hyperion to add OpenCV grabber. As far as I understand, OpenCV is much better in terms of supporting capturing images from different devices in different pixel formats. Also, OpenCV is cross-platform, so potentially it can be used in all 3 major platforms. Also, OpenCV is highly optimized.
Grabber can be enabled with ENABLE_OPENCV=ON CMake parameter, you need to have OpenCV installed. Tested on OpenCV 2.4 on Raspbian.
Configuration changes: on top level I've added a section for OpenCV grabber
```
"opencvgrabber" : …
```
> Add frame grabber using OpenCV

- bin/install_hyperion.sh
- bin/remove_hyperion.sh
On my target platform there are multiple hyperion-x11 processes and after a few restarts the led strip starts to flicker. The install and remove script should also kill these processes
No changes in the .conf file
No open issue for this change
> also kill 'hyperion-x11' processes
